/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoAdatos.AlumnoData;
import accesoAdatos.InscripcionData;
import accesoAdatos.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author 54266
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; //este es para crear la tabla
    private MateriaData mD;
    private AlumnoData aD;
    private InscripcionData iD;
    private ArrayList<Alumno> listaAlumnos;
    private ArrayList<Inscripcion> listaInscriptas;
    private ArrayList<Materia> listaNoInscriptas;

    public VistaInscripcion() {
        initComponents();
        mD = new MateriaData();
        aD = new AlumnoData();
        iD = new InscripcionData();
        modelo = new DefaultTableModel();
//        armarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opcionAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        checkInscriptas = new javax.swing.JRadioButton();
        checkNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("FORMULARIO DE INSCRIPCION");

        jLabel2.setText("Alumno:");

        opcionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setText("LISTADO DE MATERIAS");

        checkInscriptas.setText("Inscriptas");
        checkInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInscriptasActionPerformed(evt);
            }
        });

        checkNoInscriptas.setText("No Inscriptas");
        checkNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNoInscriptasActionPerformed(evt);
            }
        });

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaterias);

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular Inscripcion");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(opcionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(checkInscriptas)
                        .addGap(64, 64, 64)
                        .addComponent(checkNoInscriptas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnInscribir)
                        .addGap(55, 55, 55)
                        .addComponent(btnAnular)
                        .addGap(55, 55, 55)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(156, 156, 156))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(opcionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInscriptas)
                    .addComponent(checkNoInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnular)
                    .addComponent(btnSalir))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //para cargar los alumnos al comboBox
        listaAlumnos = (ArrayList) aD.listarAlumnos(); //el arrayList entre parentesis es para castear una List a ArrayList

        for (Alumno aux : listaAlumnos) {
            opcionAlumno.addItem(aux);
        }

        //para cargar los datos de inscripcion a la tabla
        //columnas:
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Materias");
        columnas.add("Año");

        for (Object columna : columnas) {
            modelo.addColumn(columna);   //para agregarle columna x columna recorremos con un for each la lista columnas
        }

        tablaMaterias.setModel(modelo); //le setemos por ultimo el modelo a la tabla


    }//GEN-LAST:event_formInternalFrameOpened

    private void checkInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInscriptasActionPerformed
        CargarTablaInsc();
        checkNoInscriptas.setSelected(false);
    }//GEN-LAST:event_checkInscriptasActionPerformed

    private void checkNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNoInscriptasActionPerformed
        CargarTablaNoInsc();
        checkInscriptas.setSelected(false);
    }//GEN-LAST:event_checkNoInscriptasActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
//       //OBTENER OBJETO ALUMNO DEL COMBOBOX
        Alumno a1 = (Alumno) opcionAlumno.getSelectedItem();
        //OBTENER VALORES DE LA FILA SELECCIONADA DE LA TABLA
       
        int id = (int) modelo.getValueAt(tablaMaterias.getSelectedRow(), 0);
        String nombre = (String) modelo.getValueAt(tablaMaterias.getSelectedRow(), 1);
        System.out.println(nombre);
        int año = (int) modelo.getValueAt(tablaMaterias.getSelectedRow(), 2);
        System.out.println(año);
        boolean estado = true;

        Materia m1 = new Materia(id, nombre, año, estado);

//       int idAlumno = a1.getId_alumno();
//       int idMateria = m1.getId_materia();
        Inscripcion i1 = new Inscripcion(0, a1, m1);
        iD.inscribir(i1);
        modelo.removeRow(tablaMaterias.getSelectedRow()); //borrar fila seleccionada
       

    }//GEN-LAST:event_btnInscribirActionPerformed

    private void opcionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAlumnoActionPerformed
        limpiar();
    }//GEN-LAST:event_opcionAlumnoActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
       Alumno a1 = (Alumno)opcionAlumno.getSelectedItem();
       int idAlumno =  a1.getId_alumno();
       int idMateria = (int) modelo.getValueAt(tablaMaterias.getSelectedRow(), 0);
        
        iD.borrarInscripcion(idAlumno, idMateria);
        modelo.removeRow(tablaMaterias.getSelectedRow()); //borrar fila seleccionada
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

//    public void armarTabla(){
//        //para cargar los datos de inscripcion a la tabla
//             //columnas:
//        ArrayList<Object> columnas = new ArrayList<Object>();
//        columnas.add("ID");
//        columnas.add("Materias");
//        columnas.add("Año");
//        
//        for (Object columna : columnas) {
//            modelo.addColumn(columna);   //para agregarle columna x columna recorremos con un for each la lista columnas
//        }
//        
//        tablaMaterias.setModel(modelo); //le setemos por ultimo el modelo a la tabla
//    }
    public void borrarFilas() {
        int filas = modelo.getRowCount() - 1; //saber cantidad de filas

        for (int i = filas; i >= 0; i--) {   //recorre para borralas una x una
            modelo.removeRow(i);
        }

    }

    public void CargarTablaInsc() {
        borrarFilas();
        Alumno a1 = (Alumno) opcionAlumno.getSelectedItem();//castear el objeto del combo box a un objeto alumno

        listaInscriptas = (ArrayList) iD.inscripcionesPorAlumno(a1.getId_alumno());

        for (Inscripcion aux : listaInscriptas) {
            modelo.addRow(new Object[]{aux.getMateriaI().getId_materia(), aux.getMateriaI().getNombre(), aux.getMateriaI().getAño()});  //cremos la fila de la tabla agregandole valor a sus 3 columnas
        }
    }

    public void CargarTablaNoInsc() {
        borrarFilas();
        Alumno a1 = (Alumno) opcionAlumno.getSelectedItem();//castear el objeto del combo box a un objeto alumno

        listaNoInscriptas = (ArrayList) iD.noInscriptas(a1.getId_alumno());

        for (Materia aux : listaNoInscriptas) {
            modelo.addRow(new Object[]{aux.getId_materia(), aux.getNombre(), aux.getAño()});  //cremos la fila de la tabla agregandole valor a sus 3 columnas
        }
    }
    public void limpiar(){
        checkInscriptas.setSelected(false);
        checkNoInscriptas.setSelected(false);
        
        modelo.setRowCount(0); //borrar datos de tabla
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton checkInscriptas;
    private javax.swing.JRadioButton checkNoInscriptas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Alumno> opcionAlumno;
    private javax.swing.JTable tablaMaterias;
    // End of variables declaration//GEN-END:variables
}
